defaults:
- user: default
- machine: local
- callback: base
- data: bop
- model: ISM_sam_self_grounding #_new_geo # ISM_sam_prompt #ISM_sam # ISM_sam_self_grounding # #ISM_fastsam
- _self_
- override hydra/hydra_logging: disabled
- override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

save_dir: ./log/${name_exp}
name_exp: initial
dataset_name: tless
